### ISSUE TITLE
Is it possible to have multi stage build?

### ISSUE THREAD

**Issue by saiqulhaq** [rails/devcontainer#44]
Usually I use this repo https://github.com/nickjj/docker-rails-example for my new Rails app because it has very fast build speed.
Does devcontainer also support it? as an example: https://github.com/nickjj/docker-rails-example/blob/main/Dockerfile

**Comment by andrewn617** [comment]
Hi. Yes multi-stage build is possible with dev containers. However, the dockerfile that [ships with the rails app development container](https://github.com/rails/rails/blob/main/railties/lib/rails/generators/rails/devcontainer/templates/devcontainer/Dockerfile.tt) is just pulling from an image so there is no benefit to a multi stage build. 

However, you can use a multi-stage build in your app's dev container if it makes sense. [More info](https://containers.dev/implementors/spec/#dockerfile-based).
