### ISSUE TITLE
Connecting to Postgres from GUI app

### ISSUE THREAD

**Issue by rctneil** [rails/devcontainer#45]
Hi,

In order to be able to successfully connect to PG from a GUI app on my Mac, I had to add:

```
    ports:
    - '5432:5432'
```

to `compose.yaml` under the `postgres` service.

Can this be added by default to make it easier for people to jump right into their databases externally?

**Comment by rafaelfranca** [comment]
I personally don't use GUI apps on MacOS, so I'm so keen to add it by default if it isn't required to work in Rails. The devcontainer configuration is just a suggestion. You are free to change it in the way that better suites your workflow.

**Comment by rctneil** [comment]
Took me a while to figure out why it wouldn't work as I saw the forwarding ports section of the json file so I expected that to cover it.   I'd recommend adding it as a comment at the very least for those who want to access via a GUI

**Comment by rctneil** [comment]
@rafaelfranca Can you please explain what this is for then:

```
  // Use 'forwardPorts' to make a list of ports inside the container available locally.
  "forwardPorts": [3000, 5432, 6379],
```

Having this in the `devcontainer.json` file messed me up, as I was expecting it to work with the GUI app with just this.

I bit more explanation and clarification around these would be amazing.

Thanks in advance!

**Comment by rctneil** [comment]
Hey @rafaelfranca Can you help with an explanation for the above?  Would love to know the difference.

Thanks!
