### ISSUE TITLE
Many images missing ruby

### ISSUE THREAD

**Issue by drewblas** [rails/devcontainer#46]
I tried pulling a 3.1.5, as well as a few other images and they lack ruby:

```
docker run -it ghcr.io/rails/devcontainer/images/ruby:3.1.5 zsh
root ➜ / $ gem
zsh: command not found: gem
```

Happens both on local (Docker+apple-silicon) and codespaces

I believe maybe this is a duplicate of #28 but looks like many latest published images are still affected?   If they can't be fixed, would pulling those images entirely be an option?  Seems ruby images with no ruby aren't much use.

**Comment by drewblas** [comment]
Thank you!  I have `"remoteUser": "vscode",` set in the devcontainer.json but it still doesn't find it, but that must be a different issue.

**Comment by andrewn617** [comment]
Hi @drewblas is it possible you still have the earlier defective version on your machine? We overwrite the `ruby:3.1.5` tag with the latest version, but if you have an image for that tag on your machine docker will not pull a new version.
