### ISSUE TITLE
bundler-data-permissions.sh source?

### ISSUE THREAD

**Issue by wwahammy** [rails/devcontainer#53]
Hey all, I'm trying to understand how the dev container features work and I saw the reference to `bundler-data-permissions.sh` in the bundler-cache feature: 

https://github.com/rails/devcontainer/blob/e0a7118eb5bdc666fa5e60bed60521c7b98a6a1c/features/bundler-cache/devcontainer-feature.json#L16

Is that supposed to be included in this repo? If not, where exactly does that come from? I'm trying to find it all over the place and I don't see it.

**Comment by JeremiahChurch** [comment]
The file is built by the install.sh file that is packaged with the feature - all it does is make sure the user has permission on the bundle folder since it's a mounted external volume

https://github.com/rails/devcontainer/blob/main/features/bundler-cache/install.sh#L9

**Comment by andrewn617** [comment]
Yes @JeremiahChurch is correct. But I think we can simplify this since I agree it is a bit confusing. See https://github.com/rails/devcontainer/pull/56
