### ISSUE TITLE
Can't connect to postgres

### ISSUE THREAD

**Issue by markbrown4** [rails/devcontainer#57]
First time trying devcontainer's and can't get it running.

Simple Rails 8 app scaffold here with postgres: https://github.com/markbrown4/skeleton

Opening in VS Code opens the Terminal and installs the gems but fails here:

```
== Preparing database ==
bin/rails aborted!
ActiveRecord::ConnectionNotEstablished: connection to server at "::1", port 5432 failed: Connection refused
```

--

Also tried running `docker compose up` from the `.devcontainer` directory which does seem to start postgres and selenium, however there's no output from `rails-app`.

```
Attaching to postgres-1, rails-app-1, selenium-1
postgres-1   | 
...
selenium-1   | 
...
```

![Screenshot 2024-10-10 at 4 31 25 pm](https://github.com/user-attachments/assets/5547129d-6872-4a75-9270-2e3f2224c250)

What am I missing?

**Comment by victorhazbun** [comment]
@markbrown4 don't attempt to connect via `localhost` instead try `postgres`. Contact me at victor@bonsailabs.io.

**Comment by viktorianer** [comment]
Please note the `"DB_HOST": "postgres"` line in the default `.devcontainer/devcontainer.json`, as well as the following block in `config/database.yml`:

```
  host: <%= ENV["DB_HOST"] %>
  username: postgres
  password: postgres
```

While using a URL will work, this isn't how the default setup is intended to function.

Running `docker compose up` won't resolve the issue, as the default configuration is designed for **Dev Containers only**. 

For more details, you can refer to my [draft PR on the example Rails app repository](https://github.com/viktorianer/rails8-devcontainer-enhancements/pull/9).

The main problem is that `docker compose` doesn’t expose any ports unless used within Dev Containers.

**Comment by viktorianer** [comment]
You’re welcome.

Regarding the localhost connection, you can check the PRs in my repository, which attempt to explain the issue:
https://github.com/viktorianer/rails8-devcontainer-enhancements/pull/5
and
https://github.com/rails/devcontainer/pull/52
