### ISSUE TITLE
Latest postgresql feature does not install libpq-dev

### ISSUE THREAD

**Issue by t27duck** [rails/devcontainer#63]
The latest release of the postgresql-client feature does not install `libpq-dev` anymore resulting in the Rails container to fail installing the `pg` gem.

A workaround until a fix is applied that worked for me... put this at the bottom of the Rails devcontainer Dockerfile:

```dockerfile
USER root
RUN apt-get update -y && apt-get -y install --no-install-recommends libpq-dev && rm -rf /var/lib/apt/lists/*
USER vscode
```

**Comment by xkraty** [comment]
+1 was about to open the same issue and the same workaround 😃

**Comment by t27duck** [comment]
Confirmed with the latest release and rebuilding from scratch, it appears to work at least for me.
