### ISSUE TITLE
Regression: Removal of `USER vscode` from Ruby Dockerfile is breaking other projects

### ISSUE THREAD

**Issue by jchilders** [rails/devcontainer#65]
This was discovered as a result of [rails/rails#53581](https://github.com/rails/rails/issues/53581).

Currently, devcontainers are failing for both `rails` and `rails-contributors`. The root cause for each appears to be the changes introduced in #51. Reverting those changes allows the devcontainers to be built without error.

See [this PR comment](https://github.com/rails/rails/pull/53585#issuecomment-2479992241) for the steps to reproduce the error. To summarize, though: reverting #51 fixes the problems in building the devcontainers for both projects.

The question is whether #51 should be reverted, or whether dependent projects should be updated.

**Comment by andrewn617** [comment]
I replied in https://github.com/rails/rails/issues/53581. I believe updating Rails' dev container is the correct move. I don't want to revert https://github.com/rails/devcontainer/pull/51
